runtime: php74
runtime_config:
  document_root: ci4bucke
handlers:
# Serve a directory as a static resource.
- url: /(.+\.(css|js))$
  static_files: assets/\1
  upload: assets/.+\.(css|js)$


# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto